[pt_table]
#partition table is 4K in size
address0 = 0xE000
address1 = 0xF000
version = 2

[[pt_entry]]
type = 16
name = "Boot2"
device = 0
address0 = 0
size0 = 0xE000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 3
name = "yocboot"
device = 0
address0 = 0x10000
size0 = 0x21000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 4
name = "IMTB"
device = 0
address0 = 0x31000
size0 = 0x2000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 5
name = "fct"
device = 0
address0 = 0x033000
size0 = 0x004000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 6
name = "envab"
device = 0
address0 = 0x037000
size0 = 0x004000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 0
name = "FW"
device = 0
address0 = 0x03B000
size0 = 0x580000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 8
name = "primb"
device = 0
address0 = 0x5BB000
size0 = 0x57F000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 9
name = "mfg"
device = 0
address0 = 0x5BB000
size0 = 0x57F000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 10
name = "kv"
device = 0
address0 = 0xB3A000
size0 = 0x020000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 11
name = "media"
device = 0
address0 = 0xB5A000
size0 = 0x491000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 12
name = "factory"
device = 0
address0 = 0xFEB000
size0 = 0x8000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 13
name = "user"
device = 0
address0 = 0xFF3000
size0 = 0x8000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 14
name = "kp"
device = 0
address0 = 0xFFB000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
